name: testverygood
description: A Very Good Project created by Very Good CLI.
version: 1.0.0+1
publish_to: none

environment:
  sdk: ^3.5.0

dependencies:
  bloc: ^8.1.4
  flutter_svg: ^1.1.6
  smooth_page_indicator: ^1.2.0+3
  flutter:
    sdk: flutter
  flutter_bloc: ^8.1.6
  shared_preferences: ^2.3.5
  camera: ^0.11.0+2
  flutter_localizations:
    sdk: flutter
  intl: ^0.19.0
  image_picker: ^0.8.7+5
  google_mlkit_text_recognition: ^0.14.0
  flutter_secure_storage: ^9.2.4
  uuid: ^4.5.1
  flutter_launcher_icons: ^0.14.3

dev_dependencies:
  bloc_test: ^9.1.7
  flutter_test:
    sdk: flutter
  mocktail: ^1.0.4
  very_good_analysis: ^7.0.0


# flutter_icons:
#   android: true
#   ios: true
#   image_path: "lib/assets/png/logo_app.png"

flutter:
  uses-material-design: true
  generate: true
  assets:
  - lib/assets/icon/
  - lib/assets/svg/
  - lib/assets/icon/active_navbar/
  - lib/assets/icon/inactive_navbar/
  - lib/assets/icon/home_icon/
  - lib/assets/icon/add_icon/
  - lib/assets/icon/components_icon/
  - lib/assets/icon/popup_icon/
  - lib/assets/icon/setting_icon/
  - lib/assets/icon/transaction_icon/
  - lib/assets/icon/figma_svg/
  - lib/assets/icon/OCR_icon/

  fonts:
    - family: Lato
      fonts:
        - asset: lib/assets/fonts/Lato-Bold.ttf
    - family: Lato_Light
      fonts:
        - asset: lib/assets/fonts/Lato-Light.ttf
    - family: Lato_Regular
      fonts:
        - asset: lib/assets/fonts/Lato-Regular.ttf
    - family: Lato_Thin
      fonts:
        - asset: lib/assets/fonts/Lato-Thin.ttf
    - family: HappyMonkey
      fonts:
        - asset: lib/assets/fonts/HappyMonkey.ttf

