name: Build At-time
on:
  schedule:
    - cron: '0 16 * * *' # 11:00 PM UTC mỗi ngày múi giờ việt nam là 16utc
  push:
    branches:
      - dev
    # paths:
    #   - "lib/**"
    #   - "test/**"
  pull_request:
    branches:
      - dev
    # paths:
    #   - "lib/**"
    #   - "test/**"

jobs:
  build-onchange:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v2

      - name: Setup Java
        uses: actions/setup-java@v1
        with:
          java-version: "12.x"

      - name: Setup Node.js
        uses: actions/setup-node@v2
        with:
          node-version: "22"

      - name: Setup flutter
        uses: subosito/flutter-action@v2
        with:
          channel: "stable"
          flutter-version: "3.27.0"

      # - name: Cache flutter build
      #   uses: actions/cache@v2
      #   with:
      #     path: |
      #       ~/.pub-cache
      #       .packages
      #       build
      #     key: ${{ runner.os }}-flutter-${{ hashFiles('lib/**', 'test/**') }}
      #     restore-keys: |
      #       ${{ runner.os }}-flutter-

      - name: Install dependencies
        run: flutter pub get

      - name: Run tests
        run: flutter test

      - name: Run analyze
        run: flutter analyze
